language: c
dist: bionic
python: 3.8
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip3 install nrfutil
  - wget https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/3.9.0/sdcc-3.9.0-amd64-unknown-linux2.5.tar.bz2 -O /tmp/sdcc-3.9.0-amd64-unknown-linux2.5.tar.bz2
  - tar xf /tmp/sdcc-3.9.0-amd64-unknown-linux2.5.tar.bz2 -C /tmp
  - sudo cp -r /tmp/sdcc-3.9.0/* /usr/local
install:
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2 -O /tmp/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
  - tar xf /tmp/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2 -C /tmp
  - wget http://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v15.x.x/nRF5_SDK_15.3.0_59ac345.zip -O /tmp/nRF5_SDK_15.3.0_59ac345.zip
  - mkdir /tmp/sdk
  - unzip -q /tmp/nRF5_SDK_15.3.0_59ac345.zip -d /tmp/sdk
script:
  - cp template/Makefile.posix.template template/Makefile.posix
  - sed -i "s/\/usr\/local/\/tmp/g" template/Makefile.posix
  - cp -r /tmp/sdk/nRF5_SDK_15.3.0_59ac345/* SDK/
  - cd keyboard
  - make -j
